spring:
  application:
    name: ms-vehicle-crud
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB
      enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 2
          initial-interval: 1000ms
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:vehicles}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

rabbitmq:
  send:
    queue:
      name: ${RABBITMQ_SEND_QUEUE:process-vehicle}
  update:
    queue:
      name: ${RABBITMQ_UPDATE_QUEUE:update-vehicle-status}